export enum EBotErrorTypes {
  ERROR_DIRECT_MESSAGE = "ERROR_DIRECT_MESSAGE",
  ERROR_SCENARIO_HANDLER = "ERROR_SCENARIO_HANDLER",
  TASK_MAX_TRIES_REACHED = "TASK_MAX_TRIES_REACHED",
  ERROR_SPAM_TO_GROUP = "ERROR_SPAM_TO_GROUP",
  ERROR_REMOVE_PHOTOS = "ERROR_REMOVE_PHOTOS",
  ERROR_SET_PHOTO = "ERROR_SET_PHOTO",
  ERROR_UPDATE_BIO = "ERROR_UPDATE_BIO",
  ERROR_HIDE_PHONE_NUMBER = "ERROR_HIDE_PHONE_NUMBER",
}
