export type JsonFileDataType1 = {
  app_id: number;
  app_hash: string;
  sdk: string;
  device: string;
  app_version: string;
  lang_pack: string;
  system_lang_pack: string;
  extra_params: string;
  twoFA: string;
  role: any;
  id: number;
  phone: string;
  username: any;
  date_of_birth: number;
  date_of_birth_integrity: string;
  is_premium: boolean;
  first_name: string;
  last_name: string;
  has_profile_pic: boolean;
  spamblock: any;
  session_file: string;
  stats_spam_count: number;
  stats_invites_count: number;
  last_connect_date: string;
  ipv6: boolean;
  last_check_time: number;
  layer: number;
  premium: boolean;
  proxy: any;
  register_time: number;
  sex: number;
};
export type JsonFileDataType2 = {
  session_file: string;
  phone: string;
  register_time: number;
  app_id: string;
  app_hash: string;
  sdk: string;
  app_version: string;
  device: string;
  last_check_time: number;
  avatar: any;
  first_name: string;
  last_name: string;
  username: string;
  twoFA: string;
  sex: number;
  lang_code: string;
  system_lang_code: string;
  proxy: any;
  ipv6: boolean;
  register_layer: number;
  device_net_token: string;
  device_auth_token: string;
  device_auth_token_sign: string;
  device_auth_token_secret: string;
};

export type JsonFileData = Partial<JsonFileDataType1> &
  Partial<JsonFileDataType2>;
